version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD= Pa55W0rd!1234*

  bitfit:
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: "Microsoft.AspNetCore.SpaProxy"
        ASPNETCORE_URLS: "https://+:443;http://+:80"
        ASPNETCORE_HTTPS_PORT: "7144"
        FrontEndUrl: "https://localhost:44447"
        SpaProxyServerUrl: "https://localhost:44447"


    image: ${DOCKER_REGISTRY-}bitfit
    build:
      context: .
      dockerfile: bitfit/Dockerfile
    
    ports:
      - "7144:443"
    depends_on:
      - db
