version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa55W0rd!1234*

  bitfit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7144:443"
    depends_on:
      - db

  bitfit-ui:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - bitfit
